#ifndef SOUND_IDS_H
#define SOUND_IDS_H

/*
Defines the sounds available to the engine and the categories they fall in.
Used with the SoundAtlas.
*/

// individual sound identifiers
enum class SoundId
{
	NO_SOUND,
	FOOTSTEP_GRASS_RUN_01,
	FOOTSTEP_GRASS_RUN_02,
	FOOTSTEP_GRASS_RUN_03,
	FOOTSTEP_GRASS_RUN_04,
	FOOTSTEP_GRASS_RUN_05,
	FOOTSTEP_GRASS_WALK_01,
	FOOTSTEP_GRASS_WALK_02,
	FOOTSTEP_GRASS_WALK_03,
	FOOTSTEP_GRASS_WALK_04,
	FOOTSTEP_GRASS_WALK_05,
	FOOTSTEP_GRAVEL_RUN_01,
	FOOTSTEP_GRAVEL_RUN_02,
	FOOTSTEP_GRAVEL_RUN_03,
	FOOTSTEP_GRAVEL_RUN_04,
	FOOTSTEP_GRAVEL_RUN_05,
	FOOTSTEP_WOOD_WALK_01,
	FOOTSTEP_WOOD_WALK_02,
	FOOTSTEP_WOOD_WALK_03,
	FOOTSTEP_WOOD_WALK_04,
	FOOTSTEP_WOOD_WALK_05,
	GUN_PISTOL_SHOT_01,
	GUN_PISTOL_SHOT_02,
	GUN_PISTOL_SHOT_03,
	GUN_PISTOL_SHOT_04,
	GUN_PISTOL_SHOT_05,
	GUN_PISTOL_SHOT_SILENCED_01,
	GUN_PISTOL_SHOT_SILENCED_02,
	GUN_PISTOL_SHOT_SILENCED_03,
	GUN_PISTOL_SHOT_SILENCED_04,
	GUN_PISTOL_SHOT_SILENCED_05,
	GUN_RIFLE_SHOT_01,
	GUN_RIFLE_SHOT_02,
	GUN_RIFLE_SHOT_03,
	GUN_RIFLE_SHOT_04,
	GUN_SHOTGUN_SAWED_OFF_SHOT_01,
	GUN_SHOTGUN_SAWED_OFF_SHOT_02,
	GUN_SHOTGUN_SAWED_OFF_SHOT_03,
	GUN_SHOTGUN_SAWED_OFF_SHOT_04,
	GUN_SHOTGUN_SHOT_01,
	GUN_SHOTGUN_SHOT_02,
	GUN_SHOTGUN_SHOT_03,
	GUN_SHOTGUN_SHOT_04,
	NUM_SOUNDS
};

// categories the individual sounds are grouped into
enum SoundType
{
  NONE,
  FOOTSTEP_GRASS_RUN,
  FOOTSTEP_GRASS_WALK,
  FOOTSTEP_WOOD_WALK,
  PISTOL_SHOT,
  PISTOL_SHOT_SILENCED,
  RIFLE_SHOT,
  SHOTGUN_SAWED_OFF_SHOT,
  SHOTGUN_SHOT,
  NUM_TYPES
};
#endif
