#ifndef SPRITESHEET_IDS_H
#define SPRITESHEET_IDS_H

/*
Defins all Spritesheets known to the engine.
TODO: MAKE SURE TO KEEP NUM_SPRITESHEETS (BELOW) UP-TO-DATE!
*/
enum class SpritesheetId
{
  NONE,

  CIVILIAN_IDLE_UP,
  CIVILIAN_IDLE_DOWN,
  CIVILIAN_IDLE_LEFT,
  CIVILIAN_IDLE_RIGHT,

  CIVILIAN_WALK_UP,
  CIVILIAN_WALK_DOWN,
	CIVILIAN_WALK_LEFT,
  CIVILIAN_WALK_RIGHT,

  CIVILIAN_RUN_UP,
  CIVILIAN_RUN_DOWN,
	CIVILIAN_RUN_LEFT,
  CIVILIAN_RUN_RIGHT,

  PLAYER_IDLE_UP,
  PLAYER_IDLE_DOWN,
	PLAYER_IDLE_LEFT,
  PLAYER_IDLE_RIGHT,

  PLAYER_WALK_UP,
  PLAYER_WALK_DOWN,
	PLAYER_WALK_LEFT,
  PLAYER_WALK_RIGHT,

  PLAYER_RUN_UP,
  PLAYER_RUN_DOWN,
	PLAYER_RUN_LEFT,
  PLAYER_RUN_RIGHT
};

namespace SpritesheetIds
{
  final int NUM_SPRITESHEETS = 25;
}
#endif
