#ifndef TEXTURE_IDS_H
#define TEXTURE_IDS_H

/*
Specifies the ids of all textures known to the game engine. Used with TextureAtlas.
*/
enum class TextureId
{
	NONE,  // actually a black square
	TILE_GRASS,
	TILE_BROWN_BRICK,
	TILE_DARK_BRICK,
	TILE_WHITE_BRICK,
	TILE_WATER,

	OBJECT_TREE_1,
	OBJECT_TREE_2,
	OBJECT_ROCK_1,
	OBJECT_ROCK_2,
	OBJECT_WOODEN_FENCE_LEFT,
	OBJECT_WOODEN_FENCE_POST,
	OBJECT_WOODEN_FENCE_VERT,

	CIVILIAN_IDLE_RIGHT,
	CIVILIAN_IDLE_LEFT,
	CIVILIAN_IDLE_UP,
	CIVILIAN_IDLE_DOWN,

	CIVILIAN_WALK_RIGHT,
	CIVILIAN_WALK_LEFT,
	CIVILIAN_WALK_UP,
	CIVILIAN_WALK_DOWN,

	CIVILIAN_RUN_RIGHT,
	CIVILIAN_RUN_LEFT,
	CIVILIAN_RUN_UP,
	CIVILIAN_RUN_DOWN,

	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	PLAYER_IDLE_UP,
	PLAYER_IDLE_DOWN,

	PLAYER_WALK_RIGHT,
	PLAYER_WALK_LEFT,
	PLAYER_WALK_UP,
	PLAYER_WALK_DOWN,

	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	PLAYER_RUN_UP,
	PLAYER_RUN_DOWN,

	OBJECT_PISTOL_1,
	BREAD_LOAF,
	CHICKEN_LEG,
	BEER_MUG,
	SWORD_1,
	POTION_GREEN,
	SCROLL_1,
	MOVING_BULLET,

	TEXTURE_PISTOL_AMMO,
	TEXTURE_SHOTGUN_AMMO,
	TEXTURE_RIFLE_AMMO,
	TEXTURE_SHOTGUN,
	TEXTURE_TOMMYGUN,
	TEXTURE_MUZZLE_FLASH
};

namespace TextureIds
{
	const int NUM_TEXTURES = 51;
}

#endif
